More helpful error if sass not found
Python subprocess module doesn't give a great error when a program is
not found:

    OSError: [Errno 2] No such file or directory

so I borrowed the approach used in the babel filter, which makes the
error message much nicer:

    webassets.exceptions.FilterError: Program file not found: sass.